// Объявления инструментов бота. Вынесены из bot.ts: это чистые данные,
// объём (≈235 строк) мешал читать логику. Состав и схемы не изменены.
import { plannerTools, plannerSummaryTool } from '../planner'

export const TOOLS = [
  { name:'add_expense', description:'Записать трату С ЛЮБОГО источника (дебет ИЛИ кредитная карта). ЕДИНСТВЕННЫЙ инструмент для трат — не комбинируй с mark_card_payment, иначе трата запишется дважды. Обязательно укажи source; если пользователь не сказал откуда — спроси.',
    input_schema:{type:'object',properties:{amount:{type:'number'},category:{type:'string',enum:['Еда и кафе','Транспорт','Здоровье','Развлечения','Одежда','Инвестиции','Прочее']},description:{type:'string'},source:{type:'string',enum:['debit','credit_tbank','credit_sber','split'],description:'Откуда списано: debit — Сбер дебет (уменьшает баланс); credit_tbank / credit_sber / split — кредитная карта (растёт долг, дебет не трогается)'}},required:['amount','source']} },
  { name:'delete_expense', description:'Удалить трату. По умолчанию последнюю (id="last") или по фрагменту id.',
    input_schema:{type:'object',properties:{id:{type:'string'}}} },
  { name:'add_client', description:'Записать закрытого клиента/сделку. Грейд g3/g4/g56/g78/g9/g10.',
    input_schema:{type:'object',properties:{grade:{type:'string'},revenue:{type:'number'}},required:['grade']} },
  { name:'add_goal', description:'Добавить цель/плановую покупку. month_key="2026-06" для конкретного месяца или null для накопления.',
    input_schema:{type:'object',properties:{name:{type:'string'},amount:{type:'number'},month_key:{type:['string','null']}},required:['name','amount']} },
  { name:'mark_goal_bought', description:'Отметить цель купленной (спишет с дебета).',
    input_schema:{type:'object',properties:{name:{type:'string'}},required:['name']} },
  { name:'mark_salary', description:'Отметить получение зарплаты. part="advance" (аванс) или "eom" (зп+бонус в конце месяца).',
    input_schema:{type:'object',properties:{part:{type:'string',enum:['advance','eom']}},required:['part']} },
  { name:'mark_single_fixed', description:'Отметить оплату одной постоянной траты по названию (спишет с дебета).',
    input_schema:{type:'object',properties:{name:{type:'string'},amount:{type:'number'}},required:['name']} },
  { name:'mark_fixed_paid', description:'Отметить оплату ВСЕХ неоплаченных постоянных трат разом.',
    input_schema:{type:'object',properties:{}} },
  { name:'mark_fixed_paid_with_amount', description:'Отметить оплату постоянной траты с указанием ФАКТИЧЕСКОЙ суммы (если отличается от плановой). Используй вместо mark_single_fixed когда пользователь говорит "заплатил X за Y" и X ≠ плановой сумме.',
    input_schema:{type:'object',properties:{name:{type:'string'},actual_amount:{type:'number',description:'Фактически уплаченная сумма'}},required:['name','actual_amount']} },
  { name:'mark_loan_paid', description:'Отметить оплату ежемесячного платежа по кредиту (по названию).',
    input_schema:{type:'object',properties:{name:{type:'string'}},required:['name']} },
  { name:'early_repay', description:'Досрочное погашение кредита: уменьшить тело на сумму, пересчитать платёж.',
    input_schema:{type:'object',properties:{name:{type:'string'},amount:{type:'number'}},required:['name','amount']} },
  { name:'add_income_event', description:'Разовый доход (отпускные, премия, возврат). Зачислит на дебет.',
    input_schema:{type:'object',properties:{amount:{type:'number'},description:{type:'string'}},required:['amount']} },
  { name:'mark_recurring_received', description:'Регулярная выплата получена (стипендия и т.п.). Зачислит на дебет и пометит чтобы не дублировать в прогнозе. Используй для "получил стипендию".',
    input_schema:{type:'object',properties:{name:{type:'string'},amount:{type:'number'}},required:['name']} },
  { name:'set_balance', description:'Установить баланс счёта вручную. account="sber" или "tbank".',
    input_schema:{type:'object',properties:{account:{type:'string',enum:['sber','tbank']},amount:{type:'number'}},required:['account','amount']} },
  { name:'close_month', description:'Закрыть текущий месяц.',
    input_schema:{type:'object',properties:{}} },
  { name:'add_fixed_cost', description:'Добавить новую постоянную трату (только имя и сумма, без категории).',
    input_schema:{type:'object',properties:{name:{type:'string'},amount:{type:'number'}},required:['name','amount']} },
  { name:'remove_fixed_cost', description:'Удалить постоянную трату по названию.',
    input_schema:{type:'object',properties:{name:{type:'string'}},required:['name']} },
  { name:'edit_fixed_cost', description:'Изменить постоянную трату: новое имя и/или сумму.',
    input_schema:{type:'object',properties:{name:{type:'string'},new_name:{type:'string'},amount:{type:'number'}},required:['name']} },
  { name:'update_loan', description:'Обновить параметры кредита (тело долга, ставку, платёж, дату окончания). Используй когда пользователь сообщает актуальные данные из банка или исправляет информацию.',
    input_schema:{type:'object',properties:{name:{type:'string',description:'Название кредита (фрагмент для поиска)'},principal:{type:'number',description:'Новое тело долга'},rate:{type:'number',description:'Новая ставка (например 0.34)'},min_payment:{type:'number',description:'Новый ежемесячный платёж'},end_date:{type:'string',description:'Дата окончания YYYY-MM-DD'}},required:['name']} },
  { name:'update_settings', description:'Изменить настройку. field: salary_net/salary_gross/ytd_gross/threshold/moment_share/margin_share/var_budget, или nominal с key=g3..g10.',
    input_schema:{type:'object',properties:{field:{type:'string'},value:{type:'number'},key:{type:'string'}},required:['field','value']} },
  { name:'update_salary', description:'Обновить оклад если изменился. Вызывай при: "зарплата теперь X", "оклад повысили до X". Пересчитывает дневную ставку и якоря.',
    input_schema:{type:'object',properties:{salary_net:{type:'number',description:'Чистый оклад (net) в рублях'},salary_gross:{type:'number',description:'Грязный оклад (gross), опционально'}},required:['salary_net']} },
  { name:'scenario_analysis', description:'Рассчитать экономику решения о покупке. Используй когда спрашивают "стоит ли купить X в кредит/рассрочку", "выгодно ли брать кредит", "лучше ли подождать бонуса". Возвращает сравнение: кредит vs наличные vs ожидание, с переплатой и рекомендацией.',
    input_schema:{type:'object',properties:{itemCost:{type:'number',description:'Стоимость покупки в рублях'},loanRate:{type:'number',description:'Годовая ставка кредита (например 0.33 для 33%)'},loanMonths:{type:'number',description:'Срок в месяцах'},expectedBonus:{type:'number',description:'Ожидаемый бонус (если есть)'},weeksUntilBonus:{type:'number',description:'Через сколько недель бонус'}},required:['itemCost','loanRate','loanMonths']} },
  { name:'suggest_early_repayment', description:'Рассчитать выгоду от досрочного погашения кредита при текущей ликвидности. Используй когда спрашивают "куда вложить свободные деньги" или проактивно.',
    input_schema:{type:'object',properties:{}} },
  { name:'record_vacation_pay',
    description:'Записать отпускные или больничные. Зачисляет на дебет СРАЗУ. Из ближайшего аванса/зп вычитается дневная ставка×кол-во дней. Вызывай когда "получил отпускные X₽ за N дней" или "больничный N дней, пришло X₽".',
    input_schema:{type:'object',properties:{
      days:{type:'number',description:'Количество дней'},
      paid_amount:{type:'number',description:'Сумма отпускных/больничных'},
      start_date:{type:'string',description:'Дата начала YYYY-MM-DD'},
      vacation_type:{type:'string',enum:['vacation','sick'],description:'Тип: отпуск или больничный'},
      part:{type:'string',enum:['advance','eom'],description:'Откуда вычитать дни: advance (аванс) или eom (ЗП конца месяца). Указывай если пользователь сказал явно.'}
    },required:['days','paid_amount']} },
  { name:'create_custom_category',
    description:'Создать кастомную категорию трат с опциональным лимитом и ключевыми словами.',
    input_schema:{type:'object',properties:{
      name:{type:'string'},
      monthly_limit:{type:'number'},
      keywords:{type:'array',items:{type:'string'}}
    },required:['name']} },
  { name:'add_keyword',
    description:'Добавить ключевое слово в кастомную категорию для автоматического распознавания.',
    input_schema:{type:'object',properties:{
      category_name:{type:'string'},
      keyword:{type:'string'}
    },required:['category_name','keyword']} },
  { name:'remove_custom_category',
    description:'Удалить кастомную категорию.',
    input_schema:{type:'object',properties:{name:{type:'string'}},required:['name']} },
  { name:'learn_mapping',
    description:'Запомнить соответствие trigger→категория. Вызывай после любой траты где определил категорию сам или пользователь подтвердил/поправил.',
    input_schema:{type:'object',properties:{
      trigger:{type:'string',description:'Слово/фраза из описания траты'},
      category:{type:'string'},
      custom_category_name:{type:'string'}
    },required:['trigger']} },
  { name:'save_correction',
    description:'Сохранить ПРАВИЛО ПОВЕДЕНИЯ после ошибки. Вызывай когда пользователь говорит "неверно", "ты ошибся", "не так". ЗАПРЕЩЕНО передавать сюда конкретные суммы — числа живут в БД. Формулируй правило обобщённо: не "долг карты 71252₽", а "долг карты брать из БД, не из истории диалога".',
    input_schema:{type:'object',properties:{
      bot_answered:{type:'string',description:'Что ответил бот (неверно) — первые 500 символов'},
      correction:{type:'string',description:'Правило БЕЗ цифр: как надо себя вести в подобной ситуации впредь'},
      category:{type:'string',enum:['rule','format','mapping'],description:'rule — логика/формула, format — оформление ответа, mapping — отнесение трат к категориям'}
    },required:['bot_answered','correction']} },
  { name:'list_corrections',
    description:'Показать сохранённые правила поведения. Вызывай при "чему ты научился", "какие правила помнишь".',
    input_schema:{type:'object',properties:{}} },
  { name:'delete_correction',
    description:'Удалить устаревшее правило поведения. Вызывай при "забудь это правило", "это правило неактуально".',
    input_schema:{type:'object',properties:{
      fragment:{type:'string',description:'Фрагмент текста правила для поиска и удаления'}
    },required:['fragment']} },
  { name:'undo', description:'Отменить последнее изменение (откат к снапшоту).',
    input_schema:{type:'object',properties:{}} },
  { name: 'reclassify_expense',
    description: 'Изменить категорию существующих трат текущего месяца. Вызывай когда пользователь говорит "перенеси снюс в Вредные", "это вредная трата", "перенеси авиабилет во Внеплановые", "отнеси X к категории Y". ВАЖНО: категория "Внеплановые" выносит трату ЗА лимит переменных (для крупных разовых: авиабилеты, техника). Категория "Вредные расходы" для снюса/вейпа/алкоголя. Указывай keyword (слово из описания траты) и new_category.',
    input_schema: {
      type: 'object',
      properties: {
        keyword: { type: 'string', description: 'ключевое слово в description траты' },
        new_category: { type: 'string' },
        custom_category_name: { type: 'string' },
      },
    } },
  { name: 'update_cashflow',
    description: 'Обновить плановые суммы аванса, ЗП или бонуса в текущем месяце. Вызывай когда: пользователь поправляет цифры входов, после расчёта отпускных/больничных, при несовпадении с контекстом.',
    input_schema: {
      type: 'object',
      properties: {
        adv_amount:   { type: 'number', description: 'новая сумма аванса' },
        eom_amount:   { type: 'number', description: 'новая сумма ЗП' },
        bonus_amount: { type: 'number', description: 'новая сумма бонуса' },
      },
    } },
  { name: 'update_revenue',
    description: 'Обновить выручку и/или клиентов за прошлый или текущий месяц. Вызывай когда пользователь говорит "выручка за май была X", "скорректируй выручку", "добавь клиента за прошлый месяц". После обновления бонус следующего месяца пересчитается автоматически.',
    input_schema: { type: 'object', properties: {
      month_key: { type: 'string', description: 'YYYY-MM (необязательно, по умолчанию предыдущий месяц)' },
      revenue: { type: 'number', description: 'новая выручка за месяц' },
      clients: { type: 'object', description: 'новые клиенты {grade: count}' },
    } } },
  { name: 'add_backlog_item',
    description: 'Записать задачу/идею/баг в бэклог разработки бота. ОБЯЗАТЕЛЬНО вызывай когда пользователь говорит: "запиши в бэклог", "добавь задачу", "надо сделать", "реализуй в следующем спринте", "не хватает инструмента [X]". НИКОГДА не пиши "Записал" без реального вызова этого инструмента.',
    input_schema: {
      type: 'object',
      properties: {
        title:       { type: 'string' },
        description: { type: 'string' },
        priority:    { type: 'number', description: '1=критично 2=важно 3=улучшение' },
        category:    { type: 'string', enum: ['tool', 'bug', 'feature', 'data', 'prompt'] },
      },
      required: ['title'],
    } },
  { name: 'add_multiday_expense',
    description: 'Записать трату рассчитанную на несколько дней (продукты, товары длительного пользования). Вызывай когда пользователь говорит "купил продукты на 5 дней", "взял запас на неделю", "это на N дней".',
    input_schema: {
      type: 'object',
      properties: {
        amount:      { type: 'number' },
        category:    { type: 'string' },
        description: { type: 'string' },
        covers_days: { type: 'number', description: 'на сколько дней рассчитана трата' },
      },
      required: ['amount', 'covers_days'],
    } },
  { name:'show_balance_history',
    description:'История изменений дебетового баланса. Вызывай на: "история баланса", "как менялся дебет", "откуда деньги", "почему баланс изменился".',
    input_schema:{type:'object',properties:{limit:{type:'number',description:'Кол-во записей, по умолчанию 15'}}} },
  { name:'analyze_credit_burden',
    description:'Кредитная нагрузка в единицах рабочего дня. Вызывай на: "сколько дней работаю на банк", "кредитная нагрузка", "когда начну работать на себя", "насколько тяжелы кредиты".',
    input_schema:{type:'object',properties:{}} },
  { name:'calculate_optimal_repayment',
    description:'Оптимальная стратегия досрочного погашения из бонуса/накоплений. Вызывай на: "сколько погасить из бонуса", "куда направить квартальный бонус", "как быстрее закрыть кредиты", "стратегия погашения".',
    input_schema:{type:'object',properties:{
      available_bonus:{type:'number',description:'Сумма доступная для погашения'},
      mandatory_expenses:{type:'number',description:'Обязательные расходы периода (по умолчанию 0)'},
      safe_liquid:{type:'number',description:'Минимальная подушка (по умолчанию 50000)'},
    },required:['available_bonus']} },
  { name: 'compare_months',
    description: 'Сравнить траты текущего и прошлого месяца по категориям. Вызывай на: "как я трачу по сравнению с прошлым месяцем", "стал ли я тратить больше/меньше", "сравни месяцы".',
    input_schema: { type: 'object', properties: {} } },
  { name: 'list_backlog',
    description: 'Показать задачи бэклога разработки. Вызывай при: "что в бэклоге", "какие задачи накопились", "что планируется", "бэклог".',
    input_schema: { type: 'object', properties: { status: { type: 'string', enum: ['pending', 'done', 'all'], description: 'По умолчанию pending' } } } },
  { name: 'add_idea',
    description: 'Записать идею или пожелание в пайплайн разработки. Вызывай когда пользователь говорит: "хочу добавить X", "было бы круто если", "в следующем спринте сделай", "идея: ...", "предложение: ...". Отличие от add_backlog_item: идея — сырое пожелание, backlog — конкретная задача.',
    input_schema: { type: 'object',
      properties: {
        description: { type: 'string', description: 'Текст идеи' },
        name: { type: 'string', description: 'Краткое объяснение от бота почему важно (1 предложение)' },
        category: { type: 'string', enum: ['feature', 'bug', 'optimization', 'sprint'] },
        priority: { type: 'number', description: '1=критично, 2=нормально, 3=когда-нибудь' },
      },
      required: ['description'] } },
  { name: 'update_anchor',
    description: 'Обновить якорное значение когда пользователь подтверждает новую верную цифру. Вызывай когда пользователь говорит: "аванс теперь X", "запомни что в июле Y дней", "исправь: ЗП = Z".',
    input_schema: { type: 'object',
      properties: {
        month_key: { type: 'string', description: '2026-06, 2026-07, или global' },
        key: { type: 'string', description: 'working_days, daily_rate, advance_actual, eom_salary, forecast_end и т.п.' },
        value: { type: 'string', description: 'Новое значение' },
        formula: { type: 'string', description: 'Как посчитано (необязательно)' },
      },
      required: ['month_key', 'key', 'value'] } },
  { name: 'days_until_advance',
    description: 'Рассчитать сколько дней осталось до ближайшего аванса (15 числа). Вызывай на: "когда аванс", "сколько дней до аванса", "дней до 15", "когда придут деньги", "успею до аванса".',
    input_schema: { type: 'object', properties: {} } },
  { name: 'check_salary_pattern',
    description: 'Показать историю реальных выплат (аванс/ЗП) и средние суммы. Вызывай на: "когда обычно приходит ЗП", "сколько в среднем аванс", "история выплат", "паттерн зарплаты".',
    input_schema: { type: 'object', properties: {} } },
  { name: 'pay_card_debt',
    description: 'ПОГАСИТЬ долг по кредитной карте: долг уменьшается, дебет Сбера уменьшается на ту же сумму. Используй на «погасил карту», «внёс на кредитку», «закрыл долг по карте». Для установки точного долга без движения денег укажи set_exact=true.',
    input_schema: { type: 'object', properties: {
      card: { type: 'string', description: 'Название карты: Т-Банк / Сбер кредитка / Яндекс Сплит' },
      amount: { type: 'number', description: 'Сумма погашения, либо точный остаток долга если set_exact=true' },
      set_exact: { type: 'boolean', description: 'true — установить долг равным amount (корректировка данных, дебет не трогается)' },
    }, required: ['card', 'amount'] } },
  { name: 'mark_card_payment',
    description: 'Записать оплату с кредитной карты (Т-Банк кредитная, Сбер кредитка, Яндекс Сплит). Вызывай когда пользователь говорит "оплатил с кредитки", "с карты Т-Банк", "Яндекс Сплитом". НЕ уменьшает debit_balance.',
    input_schema: { type: 'object', properties: {
      name: { type: 'string', description: 'Т-Банк кредитная | Сбер кредитка | Яндекс Сплит' },
      amount: { type: 'number' },
      category: { type: 'string' },
      description: { type: 'string' },
    }, required: ['name', 'amount'] } },
  { name: 'validate_context',
    description: 'Проверить актуальность данных. Вызывай при: "всё верно?", "проверь данные", "расхождение в цифрах".',
    input_schema: { type: 'object', properties: {} } },
  { name: 'forecast_after_advance',
    description: 'Прогноз после получения аванса 15-го и оплаты всех постоянных. Вызывай при: "сколько останется после аванса", "что будет с деньгами после 15-го", "прогноз до зарплаты".',
    input_schema: { type: 'object', properties: {} } },
  { name: 'semantic_search',
    description: 'Поиск похожих фактов и паттернов из памяти. Вызывай когда пользователь спрашивает что-то похожее на прошлые ошибки или паттерны.',
    input_schema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } },
  { name: 'list_memories',
    description: 'Показать все сохранённые факты из долгосрочной памяти. Вызывай когда пользователь спрашивает "что ты обо мне знаешь", "что помнишь".',
    input_schema: { type: 'object', properties: {} } },
  { name: 'delete_memory',
    description: 'Удалить факт из долгосрочной памяти. Вызывай когда пользователь говорит "забудь", "это неактуально".',
    input_schema: { type: 'object', properties: {
      content_fragment: { type: 'string', description: 'Фрагмент текста записи для поиска и удаления' },
    }, required: ['content_fragment'] } },
  { name: 'save_memory',
    description: 'Сохранить важный факт или паттерн в долгосрочную память. Вызывай когда пользователь говорит "запомни", "это важно", или когда выявлен устойчивый паттерн.',
    input_schema: { type: 'object', properties: {
      content: { type: 'string' },
      category: { type: 'string' },
      importance: { type: 'number', description: '1-5, где 5 критично' },
    }, required: ['content'] } },
  // ── БЛОК ПЛАНИРОВЩИК (P-1 + P-2 + P-3 habits) ──
  ...plannerTools,
  plannerSummaryTool,
]
